package games;

import java.util.*;

public class Lottery {

    public static void PlayLottery(String[] args, Scanner input) {
        boolean playing = true;
        while (playing) {
            play(input);
            if (!playAgain(input)) {
                playing = false;
            }
        }
        System.out.println("Thanks for playing!");
        return;
    }

    // PRE: accepts scanner from main
    // POST: asks the user for a 2 digit # & compares the
    // value to one generated by computer
    // evaluates whether the user 'won' the lottery

    public static void play(Scanner input) {
        System.out.println("\nWELCOME TO THE LOTTERY!!\n");

        // Create random number generator and scanner

        Random rand = new Random();

        // Step 1: Generate a random two-digit lottery number (10 to 99)
        // && set the 2 digits of lottery number

        int lotterynumber = rand.nextInt(100); // random number between 0-99
        int lotteryDigit1 = lotterynumber / 10; // gives the tens place
        int lotteryDigit2 = lotterynumber % 10; // gives the ones place

        // could also do:
        // int lotterDigit1 = rand.nextInt(10); 0-9
        // int lotteryDigit2 = rand.nextInt(10); 0-9

        // Step 2: Prompt the user to enter a two-digit number

        System.out.print("Enter your two-digit lottery pick (00-99): ");
        String userGuess = input.nextLine();

        // Step 3:Ensure it's a valid two-digit number
        // using while loop to check
        while (userGuess.length() != 2 // check length is 2
                || !Character.isDigit(userGuess.charAt(0)) // check first char is digit
                || !Character.isDigit(userGuess.charAt(1)) // check second char is digit
        ) {
            System.out.println("Invalid input. Please enter exactly two digits.");
            userGuess = input.nextLine();
        }

        // Step 4: get the 2 digits of userGuess

        int guessDigit1 = Character.getNumericValue(userGuess.charAt(0));
        int guessDigit2 = Character.getNumericValue(userGuess.charAt(1));

        System.out.println("You guessed digits: " + guessDigit1 + " and " + guessDigit2);

        // Step 5: Display lottery number

        System.out.println("The winning digits are: " + lotteryDigit1 + " and " + lotteryDigit2);

        // Step 6: Check for types of matches & print results
        // exact match

        if (guessDigit1 == lotteryDigit1 && guessDigit2 == lotteryDigit2) {
            System.out.println("Exact match: you win $10,000");
        }

        // Step 7: Check for all digits match (in different order)

        else if (guessDigit1 == lotteryDigit2 && guessDigit2 == lotteryDigit1) {
            System.out.println("Matched all digits: you win $3,000");
        }

        // Step 8: Check for one digit match

        else if ((guessDigit1 == lotteryDigit1 || guessDigit1 == lotteryDigit2) ||
                (guessDigit2 == lotteryDigit1 || guessDigit2 == lotteryDigit2)) {
            System.out.println("Matched one digit: you win $1,000");
        }

        // Step 9: No match

        else {
            System.out.println("Sorry, no match.");
        }

    }

    //PRE: accepts scanner input
    //POST: asks the user if they want to play again and returns true if they do, false otherwise
    public static boolean playAgain(Scanner input) {
        System.out.println("Play Again (y/n)?: ");
        String again = input.nextLine();
        if (!again.equals("y") && !again.equals("n")) {
            System.out.println("Invalid input, please enter y or n");
            return playAgain(input);
        }
        return again.equals("y");
    }
}
